# Generated by Django 4.2.10 on 2024-03-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_options_remove_reviews_slug_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
