# Generated by Django 4.2.10 on 2024-03-11 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_reviews_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='likes',
            field=models.ManyToManyField(related_name='reviews_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
