# Generated by Django 4.2.10 on 2024-03-11 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_alter_reviews_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='likes',
            field=models.ManyToManyField(related_name='review_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
