# Generated by Django 4.2.10 on 2024-03-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_reviews_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(default='Like'),
        ),
    ]
