# Generated by Django 4.2.10 on 2024-03-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_like_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
